### ISSUE TITLE
Connection lost

### ISSUE THREAD

**Issue by Isaksson** [mapero/node-red-contrib-hangouts#16]
I am receiving a lot of `Connection lost, reconnecting ...` In my debug tabb.

Sometimes its only a couple off minutes between the connection is lost but everything works as it should when the connection is reestablished.

Is this a know problem?

**Comment by RayMN** [comment]
Same here only that's all I'm getting ... constantly loosing connection then reconnecting ... never really establishes a solid connection. Open since Feb 6th ... is anybody out there? :)

**Comment by Isaksson** [comment]
Have you tried to upgrade to latest Node-RED, I have been running that maybe one week now without any connection errors.

**Comment by RayMN** [comment]
@ Kristoffer, I'm running Node v6.10.0 and Node-RED v0.16.2 installed from npm v3.10.10. I will check the latest but my install isn't very old. :) But one never knows these days. :)

**Comment by Isaksson** [comment]
Yes, please do that. I don't remember what version I used before but it was not very old.
Post your result when you are done :)

**Comment by RayMN** [comment]
Those are the latest versions of each. Here is a capture of the version info ...

`xx@xxxxxx:~$ node-red -v
8 Apr 11:05:12 - [info]

Welcome to Node-RED
===================

8 Apr 11:05:12 - [info] Node-RED version: v0.16.2
8 Apr 11:05:12 - [info] Node.js  version: v6.10.0
8 Apr 11:05:12 - [info] Linux 4.8.0-41-generic x64 LE
8 Apr 11:05:12 - [info] Loading palette nodes
8 Apr 11:05:13 - [info] Dashboard version 2.3.5 started at /ui
8 Apr 11:05:13 - [warn] ------------------------------------------------------
8 Apr 11:05:13 - [warn] [rpi-gpio] Info : Ignoring Raspberry Pi specific node
8 Apr 11:05:13 - [warn] ------------------------------------------------------
8 Apr 11:05:13 - [info] Settings file  : /home/xxx/.node-red/settings.js
8 Apr 11:05:13 - [info] User directory : /home/xxx/.node-red
8 Apr 11:05:13 - [info] Flows file     : /home/xxx/.node-red/flows_node-red.json
8 Apr 11:05:13 - [warn] Communication server error: Error: listen EADDRINUSE 0.0.0.0:1880
8 Apr 11:05:13 - [error] Unable to listen on http://127.0.0.1:1880/
8 Apr 11:05:13 - [error] Error: port in use
xxx@xxxxxx:~$
xxx@xxxxxx:~$ node -v
v6.10.0
xxx@xxxxxx:~$
xxx@xxxxxx:~$ npm -v
3.10.10
xxx@xxxxxx:~$`

The errors are because it's already running as a boot level process on this virtual server.

Is there a way to gather more information on what the specific error is? I would like to make sure that I'm putting the correct information in each configuration spot too, I'm not entirely sure it's not me entering the wrong information .... the docs are a little vague on everything except getting the Oauth credentials.

**Comment by Isaksson** [comment]
I sent no actual errors that is based on this module?
What is the status on this module right now with the latest Node-RED?

**Comment by RayMN** [comment]
I have it working now .... just went out to try to set it up again and now it works ... I think I had a wrong token or something. Like I said ... I was not convinced it wasn't me. :)

**Comment by grahammoore** [comment]
Just picking this thread up but "Error: listen EADDRINUSE 0.0.0.0:1880" means you already had something running on port 1880. I suspect there was as another node-red still running (or not terminating properly) that was holding the port.

**Comment by Isaksson** [comment]
If you look in the same post with that error then you will see that he answers why that error is there :)

Great that it is working now. Closing this now when new version of Node-RED solves the issue.
